CREATE TABLE services (
  id INT AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(160) NOT NULL UNIQUE, title VARCHAR(200) NOT NULL,
  icon VARCHAR(120) NULL, hero_image VARCHAR(255) NULL, card_summary VARCHAR(300) NULL,
  content_json LONGTEXT NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE posts (
  id INT AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(200) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL,
  excerpt VARCHAR(500) NULL, body_html LONGTEXT NOT NULL, featured_image VARCHAR(255) NULL,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft', published_at DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE submissions (
  id INT AUTO_INCREMENT PRIMARY KEY, type ENUM('contact','newsletter') NOT NULL,
  name VARCHAR(200) NULL, phone VARCHAR(60) NULL, email VARCHAR(200) NULL, message TEXT NULL,
  source_page VARCHAR(255) NULL, ip VARCHAR(45) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(200) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL, name VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
